trigger:
  branches:
    include:
      - testbed

variables:
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  # ===== versioning =====
  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)

stages:

# =====================
# BUILD
# =====================
- stage: build
  displayName: Build Images
  jobs:
  - job: build
    displayName: Build & Push Images
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push Images
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name yhaodevopsacr

          echo "Building API image $(imageTag)"
          docker build \
            -t $(acrLoginServer)/$(apiImageName):$(imageTag) \
            ./$(apiPath)
          docker push $(acrLoginServer)/$(apiImageName):$(imageTag)

          echo "Building WEB image $(imageTag)"
          docker build \
            -t $(acrLoginServer)/$(webImageName):$(imageTag) \
            ./$(webPath)
          docker push $(acrLoginServer)/$(webImageName):$(imageTag)

# =====================
# DEPLOY TEST
# =====================
- stage: deploy_test
  dependsOn: build
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Deploy API & WEB to Test
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          imageTag=git-$(shortSha)

          # 检查 tags
          az acr login --name yhaodevopsacr
          api_ok=$(az acr repository show-tags --name yhaodevopsacr --repository repos-api --query "contains(@, '$imageTag')" -o tsv)
          web_ok=$(az acr repository show-tags --name yhaodevopsacr --repository repos-web --query "contains(@, '$imageTag')" -o tsv)
          if [ "$api_ok" != "true" ] || [ "$web_ok" != "true" ]; then
            echo "ERROR: tag $imageTag not found in ACR"
            az acr repository show-tags --name yhaodevopsacr --repository repos-api --top 20 || true
            az acr repository show-tags --name yhaodevopsacr --repository repos-web --top 20 || true
            exit 1
          fi

          # Deploy API
          az containerapp update --name demo-api-testbed --resource-group rg-devops-demo \
            --image yhaodevopsacr.azurecr.io/repos-api:$imageTag \
            --set-env-vars ASPNETCORE_ENVIRONMENT=Testbed

          # Deploy Web
          az containerapp update --name demo-web-testbed --resource-group rg-devops-demo \
            --image yhaodevopsacr.azurecr.io/repos-web:$imageTag \
            --set-env-vars API_BASE_URL=https://demo-api-testbed.livelyrock-263dd733.francecentral.azurecontainerapps.io VITE_ENV=Testbed

    - bash: |
        set -e
        imageTag="git-$(shortSha)"
        mkdir -p image-info
        echo "{\"apiImage\":\"yhaodevopsacr.azurecr.io/repos-api:$imageTag\",\"webImage\":\"yhaodevopsacr.azurecr.io/repos-web:$imageTag\",\"tag\":\"$imageTag\",\"commit\":\"$(Build.SourceVersion)\",\"buildId\":\"$(Build.BuildId)\"}" > image-info/image.json
        echo "az pipelines run --name pipeline-prod --resources pipelines.test_build.runId=$(Build.BuildId)" > image-info/prod-trigger.txt
        echo "生成 prod 触发命令："
        cat image-info/prod-trigger.txt
      displayName: Generate image-info and prod trigger

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: image-info
        artifact: image-info

    # Smoke test temporarily removed — re-enable after debugging

