trigger:
  branches:
    include:
      - testbed

variables:
  acrName: yhaodevopsacr
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)

stages:
# ================= BUILD =================
- stage: build
  displayName: Build & Push Images
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push API + WEB
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(acrName)

          docker build -t $(acrLoginServer)/$(apiImageName):$(imageTag) $(apiPath)
          docker push $(acrLoginServer)/$(apiImageName):$(imageTag)

          docker build -t $(acrLoginServer)/$(webImageName):$(imageTag) $(webPath)
          docker push $(acrLoginServer)/$(webImageName):$(imageTag)

    - bash: |
        mkdir -p image-info
        echo "{ \"tag\": \"$(imageTag)\", \"commit\": \"$(gitSha)\", \"branch\": \"testbed\" }" > image-info/image.json
      displayName: Generate image-info artifact

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: image-info
        artifact: image-info

# ================= DEPLOY TESTBED =================
- stage: deploy_testbed
  displayName: Deploy to TESTBED
  dependsOn: build
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Deploy API & WEB to TESTBED
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(acrName)

          rg=rg-devops-demo

          az containerapp update \
            --name demo-api-testbed \
            --resource-group $rg \
            --image $(acrLoginServer)/$(apiImageName):$(imageTag) \
            --set-env-vars ASPNETCORE_ENVIRONMENT=Testbed

          az containerapp update \
            --name demo-web-testbed \
            --resource-group $rg \
            --image $(acrLoginServer)/$(webImageName):$(imageTag) \
            --set-env-vars \
              API_BASE_URL=https://demo-api-testbed.livelyrock-263dd733.francecentral.azurecontainerapps.io \
              VITE_ENV=Testbed
