trigger:
  branches:
    include:
      - testbed

variables:
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  # ===== versioning =====
  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)

stages:

# =====================
# BUILD
# =====================
- stage: build
  displayName: Build Images
  jobs:
  - job: build
    displayName: Build & Push Images
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push Images
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name yhaodevopsacr

          echo "Building API image $(imageTag)"
          docker build \
            -t $(acrLoginServer)/$(apiImageName):$(imageTag) \
            ./$(apiPath)
          docker push $(acrLoginServer)/$(apiImageName):$(imageTag)

          echo "Building WEB image $(imageTag)"
          docker build \
            -t $(acrLoginServer)/$(webImageName):$(imageTag) \
            ./$(webPath)
          docker push $(acrLoginServer)/$(webImageName):$(imageTag)

# =====================
# DEPLOY TEST
# =====================
- stage: deploy_test
  displayName: Deploy to TESTBED
  dependsOn: build
  jobs:
  - job: deploy
    displayName: Deploy Container Apps (Testbed)
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: templates/deploy-containerapp.yml
      parameters:
        environment: Testbed
        imageTag: $(imageTag)
        apiAppName: demo-api-testbed
        webAppName: demo-web-testbed
        apiBaseUrl: https://demo-api-testbed.livelyrock-263dd733.francecentral.azurecontainerapps.io

    - bash: |
        mkdir -p image-info
        echo "{
          \"apiImage\": \"$(acrLoginServer)/$(apiImageName):$(imageTag)\",
          \"webImage\": \"$(acrLoginServer)/$(webImageName):$(imageTag)\",
          \"tag\": \"$(imageTag)\",
          \"commit\": \"$(Build.SourceVersion)\",
          \"buildId\": \"$(Build.BuildId)\"
        }" > image-info/image.json

        echo "===== IMAGE INFO ====="
        cat image-info/image.json
      displayName: Generate image info artifact

    - task: PublishPipelineArtifact@1
      displayName: Publish image info for PROMOTE
      inputs:
        targetPath: image-info
        artifact: image-info

# =====================
# SMOKE TEST
# =====================
- stage: smoke_test
  displayName: Smoke Test
  dependsOn: deploy_test
  jobs:
  - job: smoke
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Check deployed Container Apps
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e

          echo "Checking API image..."
          api_image=$(az containerapp show \
            --name demo-api-testbed \
            --resource-group rg-devops-demo \
            --query configuration.image -o tsv)
          echo "API image: $api_image"
          echo "$api_image" | grep "$(imageTag)"

          echo "Checking WEB image..."
          web_image=$(az containerapp show \
            --name demo-web-testbed \
            --resource-group rg-devops-demo \
            --query configuration.image -o tsv)
          echo "WEB image: $web_image"
          echo "$web_image" | grep "$(imageTag)"

          echo "Checking web endpoint..."
          for i in 1 2 3; do
            status=$(curl -s -o /dev/null -w "%{http_code}" \
              https://demo-web-testbed.livelyrock-263dd733.francecentral.azurecontainerapps.io || true)
            echo "HTTP code: $status"
            [ "$status" = "200" ] && exit 0
            sleep 5
          done

          echo "ERROR: web endpoint not responding"
          exit 1
