trigger:
  branches:
    include:
      - testbed

variables:
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  # ===== versioning =====
  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)
  dateTag: build-$(Build.BuildId)

stages:

# =====================
# BUILD
# =====================
- stage: build
  displayName: Build Images
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push Images
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name yhaodevopsacr

          # API
          docker build \
            -t $(acrLoginServer)/$(apiImageName):git-$(shortSha) \
            -t $(acrLoginServer)/$(apiImageName):$(envName) \
            -t $(acrLoginServer)/$(apiImageName):$(dateTag) \
            ./$(apiPath)
          docker push $acrLoginServer/$apiImageName:git-$(shortSha)

          # WEB (不传环境参数！)
          docker build \
            -t $acrLoginServer/$webImageName:git-$(shortSha) \
            -t $acrLoginServer/$webImageName:$(envName) \
            -t $acrLoginServer/$webImageName:$(dateTag) \
            ./$(webPath)
          docker push $acrLoginServer/$webImageName:git-$(shortSha)

# =====================
# DEPLOY TEST
# =====================
- stage: deploy_test
  dependsOn: build
  jobs:
  - template: templates/deploy-containerapp.yml
    parameters:
      environment: Testbed
      imageTag: git-$(shortSha)
      apiAppName: demo-api-testbed
      webAppName: demo-web-testbed
      apiBaseUrl: https://demo-api-testbed.livelyrock-263dd733.francecentral.azurecontainerapps.io

  # ---------- GENERATE IMAGE INFO (PROMOTE 核心) ----------
  - bash: |
      mkdir -p image-info
      echo "{
        \"apiImage\": \"$(acrLoginServer)/$(apiImageName):$(imageTag)\",
        \"webImage\": \"$(acrLoginServer)/$(webImageName):$(imageTag)\",
        \"tag\": \"$(imageTag)\",
        \"commit\": \"$(Build.SourceVersion)\",
        \"buildId\": \"$(Build.BuildId)\"
      }" > image-info/image.json

      echo "===== IMAGE INFO ====="
      cat image-info/image.json
    displayName: Generate image info artifact

  # ---------- PUBLISH ARTIFACT ----------
  - task: PublishPipelineArtifact@1
    displayName: Publish image info for PROMOTE
    inputs:
      targetPath: image-info
      artifact: image-info

# =====================
# SMOKE TEST
# =====================
- stage: smoke_test
  dependsOn: deploy_test
  jobs:
  - job: smoke
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Check deployed Container Apps
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          echo "Verifying API Container App image contains tag: $(imageTag)"
          api_image=$(az containerapp show --name demo-api-testbed --resource-group rg-devops-demo --query configuration.image -o tsv)
          echo "API image: $api_image"
          echo "$api_image" | grep "$(imageTag)" || (echo "ERROR: API not updated to tag $(imageTag)" && exit 1)

          echo "Verifying WEB Container App image contains tag: $(imageTag)"
          web_image=$(az containerapp show --name demo-web-testbed --resource-group rg-devops-demo --query configuration.image -o tsv)
          echo "WEB image: $web_image"
          echo "$web_image" | grep "$(imageTag)" || (echo "ERROR: WEB not updated to tag $(imageTag)" && exit 1)

          echo "Testing web endpoint (expect HTTP 200)..."
          for i in 1 2 3; do
            status=$(curl -s -o /dev/null -w "%{http_code}" https://demo-web-testbed.livelyrock-263dd733.francecentral.azurecontainerapps.io || true)
            echo "HTTP code: $status"
            if [ "$status" = "200" ]; then
              echo "Web endpoint is reachable"
              exit 0
            fi
            sleep 5
          done
          echo "ERROR: web endpoint not responding with 200" && exit 1


