trigger: none

resources:
  pipelines:
    - pipeline: test_build
      source: pipeline-test
      trigger: none

stages:
- stage: promote_prod
  displayName: Promote to PROD
  environment: prod   # ðŸ” ADO é‡ŒåŠ å®¡æ‰¹
  jobs:

  # -------- Resolve tag & release notes --------
  - job: prepare
    displayName: Resolve tag & release notes
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - download: test_build
      artifact: image-info

    - bash: |
        set -e
        tag=$(jq -r .tag $(Pipeline.Workspace)/test_build/image-info/image.json)
        echo "Promoting tag=$tag"
        echo "##vso[task.setvariable variable=ResolvedImageTag;isOutput=true]$tag"
      name: resolve
      displayName: Resolve image tag

    - bash: |
        git fetch --tags --prune || true
        git log -n 30 --pretty=format:"%h %s" > release-notes.txt
        echo "" >> release-notes.txt
        echo "Image tag: $(ResolvedImageTag)" >> release-notes.txt
      displayName: Generate release notes

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: release-notes.txt
        artifact: release-notes

  # -------- Deploy PROD --------
  - job: deploy
    dependsOn: prepare
    variables:
      imageTag: ${{ dependencies.prepare.outputs['resolve.ResolvedImageTag'] }}
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Deploy PROD
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name yhaodevopsacr
          rg=rg-devops-demo

          az containerapp update \
            --name demo-api-prod \
            --resource-group $rg \
            --image yhaodevopsacr.azurecr.io/repos-api:$(imageTag) \
            --set-env-vars ASPNETCORE_ENVIRONMENT=Production

          az containerapp update \
            --name demo-web-prod \
            --resource-group $rg \
            --image yhaodevopsacr.azurecr.io/repos-web:$(imageTag) \
            --set-env-vars \
              API_BASE_URL=https://demo-api-prod.livelyrock-263dd733.francecentral.azurecontainerapps.io \
              VITE_ENV=Production
