trigger: none  # manual run

resources:
  pipelines:
    - pipeline: test_build        # consume artifacts from pipeline-test
      source: pipeline-test       # ADO pipeline name
      branch: testbed
      trigger: none               # choose run in UI; supports rollback to old run

parameters:
- name: imageTag
  displayName: Image tag to deploy (empty -> read from selected test_build run)
  type: string
  default: ''

stages:
- stage: deploy_prod
  displayName: Promote to PROD
  jobs:
  - job: generate_release_notes
    displayName: Resolve tag & generate release notes
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - download: test_build
      artifact: image-info
      displayName: Download image-info from test_build (optional)
      continueOnError: true  # ok if no artifact; manual tag can still be used

    - bash: |
        set -e
        param_tag="${{ parameters.imageTag }}"
        artifact_json="$(Pipeline.Workspace)/test_build/image-info/image.json"

        tag_from_artifact=""
        if [ -f "$artifact_json" ]; then
          tag_from_artifact=$(
            python - <<'PY' || true
            import json, os, sys
            path = os.environ["ARTIFACT_JSON"]
            with open(path) as f:
                data = json.load(f)
            tag = data.get("tag", "")
            sys.stdout.write(tag)
            PY
          )
        else
          echo "image-info artifact not found at $artifact_json (ok if you type a tag manually)."
        fi

        final_tag="$param_tag"
        if [ -z "$final_tag" ]; then final_tag="$tag_from_artifact"; fi
        if [ -z "$final_tag" ]; then
          echo "ERROR: imageTag not provided and no artifact tag found. Provide parameters.imageTag or select a test_build run with image-info."
          exit 1
        fi

        echo "Resolved imageTag=$final_tag"
        echo "##vso[task.setvariable variable=ResolvedImageTag]$final_tag"
        echo "##vso[task.setvariable variable=imageTag;isOutput=true]$final_tag"
      env:
        ARTIFACT_JSON: $(Pipeline.Workspace)/test_build/image-info/image.json
      name: resolve_tag
      displayName: Resolve image tag from input or artifact

    - bash: |
        set -e
        imageTag="$(ResolvedImageTag)"
        echo "Generating release notes for imageTag=${imageTag}"
        git fetch --tags --prune || true
        last_tag=$(git tag --sort=-creatordate | head -n1 || true)
        if [ -z "$last_tag" ]; then
          echo "No tags found, using last 50 commits"
          git log -n 50 --pretty=format:"%h %s" > release-notes.txt
        else
          echo "Comparing to last tag: $last_tag"
          git log $last_tag..HEAD --pretty=format:"%h %s" > release-notes.txt || git log -n 50 --pretty=format:"%h %s" > release-notes.txt
        fi
        echo "Image tag: ${imageTag}" >> release-notes.txt
        echo "Generated release notes:"
        cat release-notes.txt
      displayName: Generate release notes

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: release-notes.txt
        artifact: release-notes

  - job: deploy_prod
    displayName: Deploy to PROD
    dependsOn: generate_release_notes
    variables:
      finalImageTag: $[ dependencies.generate_release_notes.outputs['resolve_tag.imageTag'] ]
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Deploy API & WEB to Prod
      env:
        IMAGE_TAG: $(finalImageTag)
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          imageTag="$IMAGE_TAG"
          if [ -z "$imageTag" ]; then
            echo "ERROR: finalImageTag is empty; ensure resolve_tag step succeeded."
            exit 1
          fi
          echo "Promoting imageTag=$imageTag to Production"

          # Validate tag existence
          az acr login --name yhaodevopsacr
          api_ok=$(az acr repository show-tags --name yhaodevopsacr --repository repos-api --query "contains(@, '$imageTag')" -o tsv)
          web_ok=$(az acr repository show-tags --name yhaodevopsacr --repository repos-web --query "contains(@, '$imageTag')" -o tsv)
          if [ "$api_ok" != "true" ] || [ "$web_ok" != "true" ]; then
            echo "ERROR: tag $imageTag not found in ACR"
            az acr repository show-tags --name yhaodevopsacr --repository repos-api --top 20 || true
            az acr repository show-tags --name yhaodevopsacr --repository repos-web --top 20 || true
            exit 1
          fi

          # Soft check AcrPull permission (warn only)
          rg=rg-devops-demo
          registryId=$(az acr show --name yhaodevopsacr --resource-group $rg --query id -o tsv)

          check_acr_pull() {
            local app_name=$1
            local principal=$2
            local registry_id=$3

            if [ -z "$principal" ]; then
              echo "WARNING: $app_name has no managed identity; ensure registry credentials or system assigned identity with AcrPull"
              return
            fi

            local assigned
            assigned=$(az role assignment list --assignee "$principal" --scope "$registry_id" --query "[?roleDefinitionName=='AcrPull'] | length(@)" -o tsv)
            if [ "$assigned" = "0" ]; then
              echo "WARNING: $app_name principal '$principal' lacks AcrPull on registry. Grant with:"
              echo "  az role assignment create --assignee $principal --role AcrPull --scope $registry_id"
            else
              echo "$app_name AcrPull check: OK"
            fi
          }

          api_principal=$(az containerapp show --name demo-api-prod --resource-group $rg --query identity.principalId -o tsv || true)
          check_acr_pull "API Container App" "$api_principal" "$registryId"

          web_principal=$(az containerapp show --name demo-web-prod --resource-group $rg --query identity.principalId -o tsv || true)
          check_acr_pull "WEB Container App" "$web_principal" "$registryId"

          # Deploy updates
          az containerapp update \
            --name demo-api-prod \
            --resource-group $rg \
            --image yhaodevopsacr.azurecr.io/repos-api:$imageTag \
            --set-env-vars ASPNETCORE_ENVIRONMENT=Production

          az containerapp update \
            --name demo-web-prod \
            --resource-group $rg \
            --image yhaodevopsacr.azurecr.io/repos-web:$imageTag \
            --set-env-vars API_BASE_URL=https://demo-api-prod.livelyrock-263dd733.francecentral.azurecontainerapps.io VITE_ENV=Production

          echo "Promote complete: $imageTag"
