trigger:
  branches:
    include:
      - testbed

variables:
  acrName: yhaodevopsacr
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)

stages:
# ================= BUILD =================
- stage: build
  displayName: Build & Push Images
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push images from services.json
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(acrName)

          TAG="$(imageTag)"
          ACR="$(acrLoginServer)"
          SERVICES_FILE="pipelines/services.json"

          if [ ! -f "$SERVICES_FILE" ]; then
            echo "❌ ERROR: $SERVICES_FILE not found"
            exit 1
          fi

          echo "Discovering services to build for testbed..."
          python - <<'PY'
          import json,os,sys
          with open('pipelines/services.json') as f:
              data=json.load(f)
          services=data.get('testbed', [])
          for s in services:
              repo=s.get('repo')
              path=s.get('buildPath')
              if path:
                  print(f"BUILD::{repo}::{path}")
              else:
                  print(f"SKIP::{repo}")
          PY
          
          while IFS='::' read -r kind repo path; do
            if [ "$kind" = "BUILD" ]; then
              echo "Building $repo from $path"
              docker build -t "$ACR/$repo:$TAG" "$path"
              docker push "$ACR/$repo:$TAG"
            else
              echo "Skipping $repo (no buildPath)"
            fi
          done < <(python - <<'PY'
          import json
          with open('pipelines/services.json') as f:
              data=json.load(f)
          for s in data.get('testbed', []):
              repo=s.get('repo')
              path=s.get('buildPath')
              if path:
                  print('BUILD::'+repo+'::'+path)
              else:
                  print('SKIP::'+repo+'::')
          PY)

    - bash: |
        mkdir -p image-info
        echo "{ \"tag\": \"$(imageTag)\", \"commit\": \"$(gitSha)\", \"branch\": \"testbed\" }" > image-info/image.json
      displayName: Generate image-info artifact

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: image-info
        artifact: image-info

# ================= DEPLOY TESTBED =================
- stage: deploy_testbed
  displayName: Deploy to TESTBED
  dependsOn: build
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - template: templates/service-deployer.yml
      parameters:
        action: deploy
        tag: $(imageTag)
        env: testbed
        servicesFile: pipelines/services.json
