trigger:
  branches:
    include:
      - testbed

variables:
  acrName: yhaodevopsacr
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)

stages:
# ================= BUILD =================
- stage: build
  displayName: Build & Push Images
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push images from services.json
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          python pipelines/scripts/build.py \
            --tag "$(imageTag)" \
            --acr-name "$(acrName)" \
            --acr-login-server "$(acrLoginServer)" \
            --services-file "pipelines/services.json"


    - bash: |
        mkdir -p image-info
        echo "{ \"tag\": \"$(imageTag)\", \"commit\": \"$(gitSha)\", \"branch\": \"testbed\" }" > image-info/image.json
      displayName: Generate image-info artifact

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: image-info
        artifact: image-info

# ================= DEPLOY TESTBED =================
- stage: deploy_testbed
  displayName: Deploy to TESTBED
  dependsOn: build
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - template: templates/service-deployer.yml
      parameters:
        action: deploy
        tag: $(imageTag)
        env: testbed
        servicesFile: pipelines/services.json
