trigger: none   # 只允许手动执行
parameters:
- name: imageTag
  displayName: Image tag to rollback to (REQUIRED)
  type: string
  default: ''
stages:
- stage: rollback_prod
  displayName: Rollback PROD
  jobs:
  - job: rollback
    displayName: Rollback API & WEB to selected tag
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - template: templates/service-deployer.yml
      parameters:
        action: rollback
        tag: ${{ parameters.imageTag }}
        env: prod
        servicesFile: pipelines/services.json
