trigger:
  branches:
    include:
      - testbed

variables:
  acrName: yhaodevopsacr
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)

stages:
# ================= BUILD =================
- stage: build
  displayName: Build & Push Images
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push images from services.json
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az acr login --name $(acrName)

          TAG="$(imageTag)"
          ACR="$(acrLoginServer)"
          SERVICES_FILE="pipelines/services.json"

          if [ ! -f "$SERVICES_FILE" ]; then
            echo "❌ ERROR: $SERVICES_FILE not found"
            exit 1
          fi

          echo "Discovering services to build..."
          export TAG ACR SERVICES_FILE
          python - <<'PY'
          import json
          import os
          import subprocess
          import sys

          tag = os.environ.get("TAG", "")
          acr = os.environ.get("ACR", "")
          services_file = os.environ.get("SERVICES_FILE", "pipelines/services.json")

          if not tag:
              print("ERROR: TAG is empty", file=sys.stderr)
              sys.exit(1)
          if not acr:
              print("ERROR: ACR is empty", file=sys.stderr)
              sys.exit(1)

          try:
              with open(services_file, "r", encoding="utf-8") as f:
                  data = json.load(f)
          except FileNotFoundError:
              print(f"ERROR: {services_file} not found", file=sys.stderr)
              sys.exit(1)

          services = data.get("services", {})
          if not services:
              print("No services found to build.")
              sys.exit(0)

          for name, svc in services.items():
              repo = svc.get("repo", "").strip()
              build = svc.get("build", {}) or {}
              path = (build.get("path") or "").strip()
              skip = bool(build.get("skip", False))

              if skip:
                  print(f"Skipping build for {name} (skip=true)")
                  continue
              if not repo or not path:
                  print(f"Skipping build for {name} (missing repo/path)")
                  continue

              image = f"{acr}/{repo}:{tag}"
              print(f"Building {name} ({repo}) from {path}")
              subprocess.run(["docker", "build", "-t", image, path], check=True)
              subprocess.run(["docker", "push", image], check=True)
          PY

    - bash: |
        mkdir -p image-info
        echo "{ \"tag\": \"$(imageTag)\", \"commit\": \"$(gitSha)\", \"branch\": \"testbed\" }" > image-info/image.json
      displayName: Generate image-info artifact

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: image-info
        artifact: image-info

# ================= DEPLOY TESTBED =================
- stage: deploy_testbed
  displayName: Deploy to TESTBED
  dependsOn: build
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - template: templates/service-deployer.yml
      parameters:
        action: deploy
        tag: $(imageTag)
        env: testbed
        servicesFile: pipelines/services.json
