trigger:
  branches:
    include:
      - testbed

variables:
  acrName: yhaodevopsacr
  acrLoginServer: yhaodevopsacr.azurecr.io
  apiImageName: repos-api
  webImageName: repos-web
  apiPath: AzureWebAp
  webPath: AzureReactApp

  gitSha: $(Build.SourceVersion)
  shortSha: $[substring(variables['Build.SourceVersion'], 0, 7)]
  imageTag: git-$(shortSha)

stages:
# ================= BUILD =================
- stage: build
  displayName: Build & Push Images
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build & Push images from services.json
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          python pipelines/scripts/build.py \
            --tag "$(imageTag)" \
            --acr-name "$(acrName)" \
            --acr-login-server "$(acrLoginServer)" \
            --services-file "pipelines/services.json"


    - bash: |
        mkdir -p image-info
        echo "{ \"tag\": \"$(imageTag)\", \"commit\": \"$(gitSha)\", \"branch\": \"testbed\" }" > image-info/image.json
      displayName: Generate image-info artifact

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: image-info
        artifact: image-info

    - task: AzureCLI@2
      displayName: Tag images as 'testbed' and push
      inputs:
        azureSubscription: sc-azure-rm
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -euo pipefail
          echo "Tagging images as 'testbed' and pushing to ACR..."

          # Use pipeline-expanded variables, but fall back to environment variables if needed
          tag="${imageTag:-$IMAGETAG}"
          acrServer="${acrLoginServer:-$ACRLOGINSERVER}"
          acrName="${acrName:-$ACRNAME}"

          az acr login --name "${acrName}"

          for svc in $(jq -r '.services | keys[]' pipelines/services.json); do
            repoName=$(jq -r ".services[\"$svc\"].repo" pipelines/services.json)
            if [ -n "$repoName" ] && [ "$repoName" != "null" ]; then
              echo "Processing $repoName"

              # Pre-flight: verify the source tag exists in ACR before pulling
              query="contains(@, '${tag}')"
              if [ "$(az acr repository show-tags --name "${acrName}" --repository "$repoName" --query "$query" -o tsv)" != "true" ]; then
                echo "ERROR: Source tag '${tag}' not found in repository '${repoName}' in ACR '${acrName}'"
                exit 1
              fi

              docker pull "${acrServer}/${repoName}:${tag}"
              docker tag "${acrServer}/${repoName}:${tag}" "${acrServer}/${repoName}:testbed"
              docker push "${acrServer}/${repoName}:testbed"

              # Verify the 'testbed' tag exists in ACR for this repository
              query="contains(@, 'testbed')"
              if [ "$(az acr repository show-tags --name "${acrName}" --repository "$repoName" --query "$query" -o tsv)" != "true" ]; then
                echo "ERROR: 'testbed' tag not found for $repoName after push"
                exit 1
              fi
            fi
          done

# ================= DEPLOY TESTBED =================
- stage: deploy_testbed
  displayName: Deploy to TESTBED
  dependsOn: build
  jobs:
  - job: deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - template: templates/service-deployer.yml
      parameters:
        action: deploy
        tag: $(imageTag)
        env: testbed
        servicesFile: pipelines/services.json
